---
name: POE-Component-IRC-Plugin-WWW-CPANRatings-RSS
version: 0.0102
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: announce CPAN ratings on IRC from RSS feed on http://cpanratings.perl.org/
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  POE: 0.9999
  POE::Component::IRC::Plugin: 0.1
  POE::Component::WWW::CPANRatings::RSS: 0.0101
  utf8: 1.06
build_requires:
  Test::More: 0
provides:
  POE::Component::IRC::Plugin::WWW::CPANRatings::RSS:
    file: lib/POE/Component/IRC/Plugin/WWW/CPANRatings/RSS.pm
    version: 0.0102
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
