---
abstract: 'announce CPAN ratings on IRC from RSS feed on http://cpanratings.perl.org/'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-WWW-CPANRatings-RSS
provides:
  POE::Component::IRC::Plugin::WWW::CPANRatings::RSS:
    file: lib/POE/Component/IRC/Plugin/WWW/CPANRatings/RSS.pm
    version: 0.0106
requires:
  POE: 0.9999
  POE::Component::IRC::Plugin: 0.1
  POE::Component::WWW::CPANRatings::RSS: 0.0101
  perl: 5.008
  utf8: 1.06
resources:
  license: http://dev.perl.org/licenses/
version: 0.0106
